spring:
  data:
    redis:
      database: 0
      host: mn-posred001.nix.vimpelcom.ru
      port: 6739
      username: tech_redis_onenumber
      password: "!rDs957-wSZ0"
      timeout: 10000
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8000